using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/announcements"),Authorize(Roles="Admin,Principal,HOD,Faculty,Student")]
public sealed class AnnouncementsController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<Announcement> Accessible(){var q=db.Announcements.AsQueryable();if(user.Role=="Student")q=q.Where(x=>x.Target=="All"||x.Target=="Students");else if(user.Role=="Faculty")q=q.Where(x=>x.Target=="All"||x.Target=="Faculty");else if(user.Role=="HOD")q=q.Where(x=>x.Target=="All"||x.Target=="HOD"||x.Target=="Faculty");return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<AnnouncementDto>>> Get([FromQuery] EntityQueryParameters p,[FromQuery] string? priority,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Title.Contains(p.Search)||x.Content.Contains(p.Search)||x.PostedByName.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(priority))q=q.Where(x=>x.Priority==priority);return Ok(await q.OrderByDescending(x=>x.Date).Select(x=>new AnnouncementDto(x.Id,x.Title,x.Content,x.Priority,x.Target,x.PostedByName,x.Date,x.Status)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<AnnouncementDto>> GetById(Guid id,CancellationToken ct){var x=await Accessible().AsNoTracking().Where(x=>x.Id==id).Select(x=>new AnnouncementDto(x.Id,x.Title,x.Content,x.Priority,x.Target,x.PostedByName,x.Date,x.Status)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult<AnnouncementDto>> Create(AnnouncementUpsertDto d,CancellationToken ct){var x=new Announcement{Title=d.Title.Trim(),Content=d.Content,Priority=d.Priority,Target=d.Target,PostedByUserId=user.UserId,PostedByName=user.Name,Date=d.Date??DateOnly.FromDateTime(DateTime.UtcNow),Status=d.Status};db.Announcements.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new AnnouncementDto(x.Id,x.Title,x.Content,x.Priority,x.Target,x.PostedByName,x.Date,x.Status));}
 [HttpPut("{id:guid}"),Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult> Update(Guid id,AnnouncementUpsertDto d,CancellationToken ct){var x=await db.Announcements.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(user.Role=="HOD"&&x.PostedByUserId!=user.UserId)return Forbid();x.Title=d.Title.Trim();x.Content=d.Content;x.Priority=d.Priority;x.Target=d.Target;x.Date=d.Date??x.Date;x.Status=d.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Announcements.FindAsync([id],ct);if(x is null)return NotFound();if(user.Role=="HOD"&&x.PostedByUserId!=user.UserId)return Forbid();db.Announcements.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
