using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/attendance"),Authorize(Roles="Admin,Principal,HOD,Faculty,Student")]
public sealed class AttendanceController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<AttendanceRecord> Accessible(){var q=db.Attendance.AsQueryable();if(user.Role=="Student")q=user.StudentId is Guid sid?q.Where(x=>x.StudentId==sid):q.Where(x=>false);else if(user.Role=="HOD")q=q.Where(x=>x.Student.Department.Code==user.Department);else if(user.Role=="Faculty")q=q.Where(x=>x.Student.Department.Code==user.Department||x.MarkedByFacultyId==user.FacultyId);return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<AttendanceDto>>> Get([FromQuery] EntityQueryParameters p,[FromQuery] DateOnly? date,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Student.Name.Contains(p.Search)||x.Student.RollNo.Contains(p.Search)||x.Subject.Name.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Student.Department.Code==p.Department);if(date.HasValue)q=q.Where(x=>x.Date==date.Value);return Ok(await q.OrderByDescending(x=>x.Date).ThenBy(x=>x.Student.RollNo).Select(x=>new AttendanceDto(x.Id,x.Student.Name,x.Student.RollNo,x.Subject.Name,x.Date,x.Status,x.MarkedByName)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<AttendanceDto>> GetById(Guid id,CancellationToken ct){var x=await Accessible().AsNoTracking().Where(x=>x.Id==id).Select(x=>new AttendanceDto(x.Id,x.Student.Name,x.Student.RollNo,x.Subject.Name,x.Date,x.Status,x.MarkedByName)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Principal,HOD,Faculty")] public async Task<ActionResult<AttendanceDto>> Create(AttendanceUpsertDto d,CancellationToken ct){var student=await db.Students.Include(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==d.StudentId,ct);var subject=await db.Subjects.Include(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==d.SubjectId,ct);if(student is null||subject is null)return BadRequest(new ApiMessage("Student or subject is invalid."));if(user.IsInRole("HOD","Faculty")&&student.Department.Code!=user.Department)return Forbid();Faculty? marker=null;var markerId=d.MarkedByFacultyId??user.FacultyId;if(markerId.HasValue)marker=await db.Faculty.FindAsync([markerId.Value],ct);var x=new AttendanceRecord{Student=student,Subject=subject,Date=d.Date,Status=d.Status,MarkedByFaculty=marker,MarkedByName=!string.IsNullOrWhiteSpace(d.MarkedBy)?d.MarkedBy:user.Name};db.Attendance.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new AttendanceDto(x.Id,student.Name,student.RollNo,subject.Name,x.Date,x.Status,x.MarkedByName));}
 [HttpPut("{id:guid}"),Authorize(Roles="Admin,Principal,HOD,Faculty")] public async Task<ActionResult> Update(Guid id,AttendanceUpsertDto d,CancellationToken ct){var x=await db.Attendance.Include(x=>x.Student).ThenInclude(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(user.IsInRole("HOD","Faculty")&&x.Student.Department.Code!=user.Department)return Forbid();var student=await db.Students.FindAsync([d.StudentId],ct);var subject=await db.Subjects.FindAsync([d.SubjectId],ct);if(student is null||subject is null)return BadRequest(new ApiMessage("Student or subject is invalid."));x.Student=student;x.Subject=subject;x.Date=d.Date;x.Status=d.Status;x.MarkedByName=!string.IsNullOrWhiteSpace(d.MarkedBy)?d.MarkedBy:user.Name;x.MarkedByFacultyId=d.MarkedByFacultyId??user.FacultyId;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Attendance.FindAsync([id],ct);if(x is null)return NotFound();db.Attendance.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
