using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/books"),Authorize(Roles="Admin,Principal")]
public sealed class BooksController(AppDbContext db):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<BookDto>>> Get([FromQuery] EntityQueryParameters p,[FromQuery] string? category,CancellationToken ct){var q=db.Books.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Title.Contains(p.Search)||x.Author.Contains(p.Search)||x.Isbn.Contains(p.Search));if(!string.IsNullOrWhiteSpace(category))q=q.Where(x=>x.Category.Name==category||x.Category.Code==category);if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);return Ok(await q.OrderBy(x=>x.Title).Select(x=>new BookDto(x.Id,x.Title,x.Isbn,x.Author,x.Category.Name,x.Copies,x.Available,x.Status)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<BookDto>> GetById(Guid id,CancellationToken ct){var x=await db.Books.AsNoTracking().Where(x=>x.Id==id).Select(x=>new BookDto(x.Id,x.Title,x.Isbn,x.Author,x.Category.Name,x.Copies,x.Available,x.Status)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<BookDto>> Create(BookUpsertDto d,CancellationToken ct){if(d.Available>d.Copies)return BadRequest(new ApiMessage("Available copies cannot exceed total copies."));var category=await db.BookCategories.FirstOrDefaultAsync(x=>x.Name==d.Category||x.Code==d.Category,ct);if(category is null)return BadRequest(new ApiMessage("Book category is invalid."));var x=new Book{Title=d.Title.Trim(),Isbn=d.Isbn.Trim(),Author=d.Author.Trim(),Category=category,Copies=d.Copies,Available=d.Available,Status=d.Status};db.Books.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new BookDto(x.Id,x.Title,x.Isbn,x.Author,category.Name,x.Copies,x.Available,x.Status));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,BookUpsertDto d,CancellationToken ct){var x=await db.Books.FindAsync([id],ct);if(x is null)return NotFound();if(d.Available>d.Copies)return BadRequest(new ApiMessage("Available copies cannot exceed total copies."));var category=await db.BookCategories.FirstOrDefaultAsync(a=>a.Name==d.Category||a.Code==d.Category,ct);if(category is null)return BadRequest(new ApiMessage("Book category is invalid."));x.Title=d.Title.Trim();x.Isbn=d.Isbn.Trim();x.Author=d.Author.Trim();x.Category=category;x.Copies=d.Copies;x.Available=d.Available;x.Status=d.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Books.FindAsync([id],ct);if(x is null)return NotFound();db.Books.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
