using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/exams"),Authorize(Roles="Admin,Principal")]
public sealed class ExamsController(AppDbContext db):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<ExamDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=db.Exams.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Name.Contains(p.Search)||x.Code.Contains(p.Search)||x.SemesterName.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);return Ok(await q.OrderByDescending(x=>x.StartDate).Select(x=>new ExamDto(x.Id,x.Name,x.Code,x.SemesterName,x.StartDate,x.EndDate,x.Type,x.Status)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<ExamDto>> GetById(Guid id,CancellationToken ct){var x=await db.Exams.AsNoTracking().Where(x=>x.Id==id).Select(x=>new ExamDto(x.Id,x.Name,x.Code,x.SemesterName,x.StartDate,x.EndDate,x.Type,x.Status)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<ExamDto>> Create(ExamUpsertDto d,CancellationToken ct){if(d.EndDate<d.StartDate)return BadRequest(new ApiMessage("End date must be after start date."));var sem=await db.Semesters.FirstOrDefaultAsync(x=>x.Name==d.Semester||x.Code==d.Semester,ct);var x=new Exam{Name=d.Name,Code=d.Code.ToUpperInvariant(),Semester=sem,SemesterName=sem?.Name??d.Semester,StartDate=d.StartDate,EndDate=d.EndDate,Type=d.Type,Status=d.Status};db.Exams.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new ExamDto(x.Id,x.Name,x.Code,x.SemesterName,x.StartDate,x.EndDate,x.Type,x.Status));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,ExamUpsertDto d,CancellationToken ct){var x=await db.Exams.FindAsync([id],ct);if(x is null)return NotFound();if(d.EndDate<d.StartDate)return BadRequest(new ApiMessage("End date must be after start date."));var sem=await db.Semesters.FirstOrDefaultAsync(a=>a.Name==d.Semester||a.Code==d.Semester,ct);x.Name=d.Name;x.Code=d.Code.ToUpperInvariant();x.Semester=sem;x.SemesterName=sem?.Name??d.Semester;x.StartDate=d.StartDate;x.EndDate=d.EndDate;x.Type=d.Type;x.Status=d.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Exams.FindAsync([id],ct);if(x is null)return NotFound();db.Exams.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
