using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/fees"),Authorize(Roles="Admin,Principal")]
public sealed class FeesController(AppDbContext db):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<FeeDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=db.Fees.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Student.Name.Contains(p.Search)||x.Student.RollNo.Contains(p.Search)||x.SemesterName.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Student.Department.Code==p.Department);return Ok(await q.OrderBy(x=>x.Student.RollNo).Select(x=>new FeeDto(x.Id,x.Student.Name,x.Student.RollNo,x.SemesterName,x.TotalFee,x.Paid,x.TotalFee-x.Paid,x.Status,x.PaidDate,x.Mode)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<FeeDto>> GetById(Guid id,CancellationToken ct){var x=await db.Fees.AsNoTracking().Where(x=>x.Id==id).Select(x=>new FeeDto(x.Id,x.Student.Name,x.Student.RollNo,x.SemesterName,x.TotalFee,x.Paid,x.TotalFee-x.Paid,x.Status,x.PaidDate,x.Mode)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<FeeDto>> Create(FeeUpsertDto d,CancellationToken ct){if(d.Paid>d.TotalFee)return BadRequest(new ApiMessage("Paid amount cannot exceed total fee."));var student=await db.Students.FindAsync([d.StudentId],ct);if(student is null)return BadRequest(new ApiMessage("Student is invalid."));var x=new FeeRecord{Student=student,SemesterName=d.Semester,TotalFee=d.TotalFee,Paid=d.Paid,Status=d.Status,PaidDate=d.PaidDate,Mode=d.Mode};db.Fees.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new FeeDto(x.Id,student.Name,student.RollNo,x.SemesterName,x.TotalFee,x.Paid,x.TotalFee-x.Paid,x.Status,x.PaidDate,x.Mode));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,FeeUpsertDto d,CancellationToken ct){var x=await db.Fees.FindAsync([id],ct);if(x is null)return NotFound();if(d.Paid>d.TotalFee)return BadRequest(new ApiMessage("Paid amount cannot exceed total fee."));var student=await db.Students.FindAsync([d.StudentId],ct);if(student is null)return BadRequest(new ApiMessage("Student is invalid."));x.Student=student;x.SemesterName=d.Semester;x.TotalFee=d.TotalFee;x.Paid=d.Paid;x.Status=d.Status;x.PaidDate=d.PaidDate;x.Mode=d.Mode;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Fees.FindAsync([id],ct);if(x is null)return NotFound();db.Fees.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
