using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/hod-authorizations"),Authorize(Roles="Admin,Principal,HOD,Faculty")]
public sealed class HodAuthorizationsController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<HodAuthorization> Accessible(){var q=db.HodAuthorizations.AsQueryable();if(user.Role=="HOD")q=q.Where(x=>x.Department.Code==user.Department);else if(user.Role=="Faculty")q=q.Where(x=>x.RequestedBy==user.Name);return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<HodAuthorizationDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Type.Contains(p.Search)||x.RequestedBy.Contains(p.Search)||x.Details.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Department.Code==p.Department);return Ok(await q.OrderByDescending(x=>x.RequestDate).Select(x=>new HodAuthorizationDto(x.Id,x.Type,x.RequestedBy,x.Department.Code,x.Details,x.Status,x.RequestDate)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpPost] public async Task<ActionResult<HodAuthorizationDto>> Create(HodAuthorizationCreateDto d,CancellationToken ct){var code=d.Department.Trim().ToUpperInvariant();if(user.Role=="HOD"||user.Role=="Faculty")code=user.Department;var dep=await db.Departments.FirstOrDefaultAsync(x=>x.Code==code,ct);if(dep is null)return BadRequest(new ApiMessage("Department is invalid."));var x=new HodAuthorization{Type=d.Type,RequestedBy=string.IsNullOrWhiteSpace(d.RequestedBy)?user.Name:d.RequestedBy,Department=dep,Details=d.Details,Status="Pending",RequestDate=d.RequestDate??DateOnly.FromDateTime(DateTime.UtcNow)};db.HodAuthorizations.Add(x);await db.SaveChangesAsync(ct);return Created("/api/hod-authorizations/"+x.Id,new HodAuthorizationDto(x.Id,x.Type,x.RequestedBy,dep.Code,x.Details,x.Status,x.RequestDate));}
 [HttpPatch("{id:guid}/decision"),Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult> Decide(Guid id,AuthorizationDecisionDto d,CancellationToken ct){var decision=d.Decision.Trim();if(decision!="Approved"&&decision!="Rejected")return BadRequest(new ApiMessage("Decision must be Approved or Rejected."));var x=await db.HodAuthorizations.Include(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(user.Role=="HOD"&&x.Department.Code!=user.Department)return Forbid();x.Status=decision;x.DecidedByUserId=user.UserId;x.DecidedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.HodAuthorizations.FindAsync([id],ct);if(x is null)return NotFound();db.HodAuthorizations.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
