using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/marks"),Authorize(Roles="Admin,Principal,HOD,Faculty")]
public sealed class MarksController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<MarkRecord> Accessible(){var q=db.Marks.AsQueryable();if(user.Role=="HOD"||user.Role=="Faculty")q=q.Where(x=>x.Student.Department.Code==user.Department);return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<MarkDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Student.Name.Contains(p.Search)||x.Student.RollNo.Contains(p.Search)||x.Subject.Name.Contains(p.Search)||x.ExamName.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Student.Department.Code==p.Department);return Ok(await q.OrderBy(x=>x.Student.RollNo).Select(x=>new MarkDto(x.Id,x.Student.Name,x.Student.RollNo,x.Subject.Name,x.ExamName,x.InternalMarks,x.ExternalMarks,x.InternalMarks+x.ExternalMarks,x.MaxMarks,x.Grade)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<MarkDto>> GetById(Guid id,CancellationToken ct){var x=await Accessible().AsNoTracking().Where(x=>x.Id==id).Select(x=>new MarkDto(x.Id,x.Student.Name,x.Student.RollNo,x.Subject.Name,x.ExamName,x.InternalMarks,x.ExternalMarks,x.InternalMarks+x.ExternalMarks,x.MaxMarks,x.Grade)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<MarkDto>> Create(MarkUpsertDto d,CancellationToken ct){var student=await db.Students.Include(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==d.StudentId,ct);var subject=await db.Subjects.FirstOrDefaultAsync(x=>x.Id==d.SubjectId,ct);if(student is null||subject is null)return BadRequest(new ApiMessage("Student or subject is invalid."));if(user.IsInRole("HOD","Faculty")&&student.Department.Code!=user.Department)return Forbid();var x=new MarkRecord{Student=student,Subject=subject,ExamName=d.Exam,InternalMarks=d.Internal,ExternalMarks=d.External,MaxMarks=d.MaxMarks,Grade=d.Grade};db.Marks.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new MarkDto(x.Id,student.Name,student.RollNo,subject.Name,x.ExamName,x.InternalMarks,x.ExternalMarks,x.InternalMarks+x.ExternalMarks,x.MaxMarks,x.Grade));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,MarkUpsertDto d,CancellationToken ct){var x=await Accessible().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();var student=await db.Students.FindAsync([d.StudentId],ct);var subject=await db.Subjects.FindAsync([d.SubjectId],ct);if(student is null||subject is null)return BadRequest(new ApiMessage("Student or subject is invalid."));x.Student=student;x.Subject=subject;x.ExamName=d.Exam;x.InternalMarks=d.Internal;x.ExternalMarks=d.External;x.MaxMarks=d.MaxMarks;x.Grade=d.Grade;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Marks.FindAsync([id],ct);if(x is null)return NotFound();db.Marks.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
