using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/notifications"),Authorize]
public sealed class NotificationsController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<Notification> Accessible(){var q=db.Notifications.AsQueryable();if(!user.IsInRole("Admin","Principal"))q=q.Where(x=>x.UserId==user.UserId||x.RecipientName==user.Name);return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<NotificationDto>>> Get([FromQuery] QueryParameters p,[FromQuery] bool? read,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Title.Contains(p.Search)||x.Message.Contains(p.Search)||x.Type.Contains(p.Search));if(read.HasValue)q=q.Where(x=>x.IsRead==read.Value);return Ok(await q.OrderByDescending(x=>x.DateUtc).Select(x=>new NotificationDto(x.Id,x.Title,x.Message,x.RecipientName,x.Type,x.IsRead,x.DateUtc)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpPost,Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult<NotificationDto>> Create(NotificationCreateDto d,CancellationToken ct){UserAccount? recipient=null;if(d.UserId.HasValue)recipient=await db.Users.FindAsync([d.UserId.Value],ct);if(recipient is null&&!string.IsNullOrWhiteSpace(d.User))recipient=await db.Users.FirstOrDefaultAsync(x=>x.Name==d.User||x.Email==d.User,ct);var x=new Notification{User=recipient,RecipientName=recipient?.Name??d.User,Title=d.Title,Message=d.Message,Type=d.Type,IsRead=false,DateUtc=DateTime.UtcNow};db.Notifications.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(Get),new{id=x.Id},new NotificationDto(x.Id,x.Title,x.Message,x.RecipientName,x.Type,x.IsRead,x.DateUtc));}
 [HttpPatch("{id:guid}/read")] public async Task<ActionResult> MarkRead(Guid id,CancellationToken ct){var x=await Accessible().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();x.IsRead=true;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPatch("read-all")] public async Task<ActionResult> MarkAllRead(CancellationToken ct){var items=await Accessible().Where(x=>!x.IsRead).ToListAsync(ct);foreach(var x in items)x.IsRead=true;await db.SaveChangesAsync(ct);return Ok(new ApiMessage($"Marked {items.Count} notifications as read."));}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await Accessible().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();db.Notifications.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
