using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/results"),Authorize(Roles="Admin,Principal,HOD,Student")]
public sealed class ResultsController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<ResultRecord> Accessible(){var q=db.Results.AsQueryable();if(user.Role=="HOD")q=q.Where(x=>x.Student.Department.Code==user.Department);else if(user.Role=="Student")q=user.StudentId is Guid sid?q.Where(x=>x.StudentId==sid):q.Where(x=>false);return q;}
 [HttpGet] public async Task<ActionResult<PagedResult<ResultDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Student.Name.Contains(p.Search)||x.Student.RollNo.Contains(p.Search)||x.SemesterName.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Student.Department.Code==p.Department);return Ok(await q.OrderByDescending(x=>x.Year).ThenBy(x=>x.Student.RollNo).Select(x=>new ResultDto(x.Id,x.Student.Name,x.Student.RollNo,x.SemesterName,x.Sgpa,x.TotalCredits,x.Status,x.Year)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<ResultDto>> GetById(Guid id,CancellationToken ct){var x=await Accessible().AsNoTracking().Where(x=>x.Id==id).Select(x=>new ResultDto(x.Id,x.Student.Name,x.Student.RollNo,x.SemesterName,x.Sgpa,x.TotalCredits,x.Status,x.Year)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult<ResultDto>> Create(ResultUpsertDto d,CancellationToken ct){var student=await db.Students.Include(x=>x.Department).FirstOrDefaultAsync(x=>x.Id==d.StudentId,ct);if(student is null)return BadRequest(new ApiMessage("Student is invalid."));if(user.Role=="HOD"&&student.Department.Code!=user.Department)return Forbid();var x=new ResultRecord{Student=student,SemesterName=d.Semester,Sgpa=d.Sgpa,TotalCredits=d.TotalCredits,Status=d.Status,Year=d.Year};db.Results.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new ResultDto(x.Id,student.Name,student.RollNo,x.SemesterName,x.Sgpa,x.TotalCredits,x.Status,x.Year));}
 [HttpPut("{id:guid}"),Authorize(Roles="Admin,Principal,HOD")] public async Task<ActionResult> Update(Guid id,ResultUpsertDto d,CancellationToken ct){var x=await Accessible().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();var student=await db.Students.FindAsync([d.StudentId],ct);if(student is null)return BadRequest(new ApiMessage("Student is invalid."));x.Student=student;x.SemesterName=d.Semester;x.Sgpa=d.Sgpa;x.TotalCredits=d.TotalCredits;x.Status=d.Status;x.Year=d.Year;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Results.FindAsync([id],ct);if(x is null)return NotFound();db.Results.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
