using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/semesters"),Authorize(Roles="Admin,Principal")]
public sealed class SemestersController(AppDbContext db):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<SemesterDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=db.Semesters.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Name.Contains(p.Search)||x.Code.Contains(p.Search)||x.AcademicYear.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);return Ok(await q.OrderBy(x=>x.StartDate).Select(x=>new SemesterDto(x.Id,x.Name,x.Code,x.AcademicYear,x.StartDate,x.EndDate,x.Status)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<SemesterDto>> GetById(Guid id,CancellationToken ct){var x=await db.Semesters.AsNoTracking().Where(x=>x.Id==id).Select(x=>new SemesterDto(x.Id,x.Name,x.Code,x.AcademicYear,x.StartDate,x.EndDate,x.Status)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<SemesterDto>> Create(SemesterUpsertDto d,CancellationToken ct){if(d.EndDate<d.StartDate)return BadRequest(new ApiMessage("End date must be after start date."));var x=new Semester{Name=d.Name,Code=d.Code.ToUpperInvariant(),AcademicYear=d.AcademicYear,StartDate=d.StartDate,EndDate=d.EndDate,Status=d.Status};db.Semesters.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new SemesterDto(x.Id,x.Name,x.Code,x.AcademicYear,x.StartDate,x.EndDate,x.Status));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,SemesterUpsertDto d,CancellationToken ct){var x=await db.Semesters.FindAsync([id],ct);if(x is null)return NotFound();if(d.EndDate<d.StartDate)return BadRequest(new ApiMessage("End date must be after start date."));x.Name=d.Name;x.Code=d.Code.ToUpperInvariant();x.AcademicYear=d.AcademicYear;x.StartDate=d.StartDate;x.EndDate=d.EndDate;x.Status=d.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Semesters.Include(x=>x.Exams).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(x.Exams.Count>0)return Conflict(new ApiMessage("Semester has related examinations."));db.Semesters.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
