using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/students"),Authorize(Roles="Admin,Principal,HOD")]
public sealed class StudentsController(AppDbContext db,CurrentUserService user):ControllerBase
{
 private IQueryable<Student> Accessible()=>user.Role=="HOD"?db.Students.Where(x=>x.Department.Code==user.Department):db.Students;
 [HttpGet] public async Task<ActionResult<PagedResult<StudentDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=Accessible().AsNoTracking();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Name.Contains(p.Search)||x.Email.Contains(p.Search)||x.RollNo.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Department.Code==p.Department);if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);return Ok(await q.OrderBy(x=>x.RollNo).Select(x=>new StudentDto(x.Id,x.Name,x.Email,x.Department.Code,x.SemesterNumber.ToString(),x.RollNo,x.Phone,x.DateOfBirth,x.Gender,x.Status,x.FeeStatus)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<StudentDto>> GetById(Guid id,CancellationToken ct){var x=await Accessible().AsNoTracking().Where(x=>x.Id==id).Select(x=>new StudentDto(x.Id,x.Name,x.Email,x.Department.Code,x.SemesterNumber.ToString(),x.RollNo,x.Phone,x.DateOfBirth,x.Gender,x.Status,x.FeeStatus)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Principal")] public async Task<ActionResult<StudentDto>> Create(StudentUpsertDto d,CancellationToken ct){var code=d.Department.Trim().ToUpperInvariant();var dep=await db.Departments.FirstOrDefaultAsync(x=>x.Code==code,ct);if(dep is null)return BadRequest(new ApiMessage("Department code is invalid."));var x=new Student{Name=d.Name.Trim(),Email=d.Email.Trim().ToLowerInvariant(),Department=dep,SemesterNumber=d.Semester,RollNo=d.RollNo.Trim().ToUpperInvariant(),Phone=d.Phone,DateOfBirth=d.Dob,Gender=d.Gender,Status=d.Status,FeeStatus=d.FeeStatus};db.Students.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new StudentDto(x.Id,x.Name,x.Email,dep.Code,x.SemesterNumber.ToString(),x.RollNo,x.Phone,x.DateOfBirth,x.Gender,x.Status,x.FeeStatus));}
 [HttpPut("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Update(Guid id,StudentUpsertDto d,CancellationToken ct){var x=await db.Students.FindAsync([id],ct);if(x is null)return NotFound();var code=d.Department.Trim().ToUpperInvariant();var dep=await db.Departments.FirstOrDefaultAsync(a=>a.Code==code,ct);if(dep is null)return BadRequest(new ApiMessage("Department code is invalid."));x.Name=d.Name.Trim();x.Email=d.Email.Trim().ToLowerInvariant();x.Department=dep;x.SemesterNumber=d.Semester;x.RollNo=d.RollNo.Trim().ToUpperInvariant();x.Phone=d.Phone;x.DateOfBirth=d.Dob;x.Gender=d.Gender;x.Status=d.Status;x.FeeStatus=d.FeeStatus;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Roles="Admin,Principal")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Students.FindAsync([id],ct);if(x is null)return NotFound();db.Students.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
