using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/subjects"),Authorize(Roles="Admin,Principal")]
public sealed class SubjectsController(AppDbContext db):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<SubjectDto>>> Get([FromQuery] EntityQueryParameters p,CancellationToken ct){var q=db.Subjects.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Name.Contains(p.Search)||x.Code.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Department.Code==p.Department);if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);return Ok(await q.OrderBy(x=>x.Name).Select(x=>new SubjectDto(x.Id,x.Name,x.Code,x.Department.Code,x.SemesterNumber.ToString(),x.Credits,x.Type,x.Status)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<SubjectDto>> GetById(Guid id,CancellationToken ct){var x=await db.Subjects.AsNoTracking().Where(x=>x.Id==id).Select(x=>new SubjectDto(x.Id,x.Name,x.Code,x.Department.Code,x.SemesterNumber.ToString(),x.Credits,x.Type,x.Status)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<SubjectDto>> Create(SubjectUpsertDto d,CancellationToken ct){var dep=await db.Departments.FirstOrDefaultAsync(x=>x.Code==d.Department,ct);if(dep is null)return BadRequest(new ApiMessage("Department code is invalid."));var x=new Subject{Name=d.Name.Trim(),Code=d.Code.Trim().ToUpperInvariant(),Department=dep,SemesterNumber=d.Semester,Credits=d.Credits,Type=d.Type,Status=d.Status};db.Subjects.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new SubjectDto(x.Id,x.Name,x.Code,dep.Code,x.SemesterNumber.ToString(),x.Credits,x.Type,x.Status));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,SubjectUpsertDto d,CancellationToken ct){var x=await db.Subjects.FindAsync([id],ct);if(x is null)return NotFound();var dep=await db.Departments.FirstOrDefaultAsync(a=>a.Code==d.Department,ct);if(dep is null)return BadRequest(new ApiMessage("Department code is invalid."));x.Name=d.Name.Trim();x.Code=d.Code.Trim().ToUpperInvariant();x.Department=dep;x.SemesterNumber=d.Semester;x.Credits=d.Credits;x.Type=d.Type;x.Status=d.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Subjects.FindAsync([id],ct);if(x is null)return NotFound();db.Subjects.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
