using CollegeERP.Api.Data; using CollegeERP.Api.DTOs; using CollegeERP.Api.Extensions; using CollegeERP.Api.Models; using CollegeERP.Api.Services;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace CollegeERP.Api.Controllers;
[ApiController,Route("api/users"),Authorize(Roles="Admin")]
public sealed class UsersController(AppDbContext db,PasswordService passwords):ControllerBase
{
 [HttpGet] public async Task<ActionResult<PagedResult<UserDto>>> Get([FromQuery] EntityQueryParameters p,[FromQuery] string? role,CancellationToken ct){var q=db.Users.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(p.Search))q=q.Where(x=>x.Name.Contains(p.Search)||x.Email.Contains(p.Search));if(!string.IsNullOrWhiteSpace(p.Status))q=q.Where(x=>x.Status==p.Status);if(!string.IsNullOrWhiteSpace(p.Department))q=q.Where(x=>x.Department!=null&&x.Department.Code==p.Department);if(!string.IsNullOrWhiteSpace(role))q=q.Where(x=>x.Role.Name==role);return Ok(await q.OrderBy(x=>x.Name).Select(x=>new UserDto(x.Id,x.Name,x.Email,x.Role.Name,x.Department!=null?x.Department.Code:"",x.Status,x.LastLoginUtc,x.Avatar,x.Color)).ToPagedResultAsync(p.Page,p.PageSize,ct));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<UserDto>> GetById(Guid id,CancellationToken ct){var x=await db.Users.AsNoTracking().Where(x=>x.Id==id).Select(x=>new UserDto(x.Id,x.Name,x.Email,x.Role.Name,x.Department!=null?x.Department.Code:"",x.Status,x.LastLoginUtc,x.Avatar,x.Color)).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [HttpPost] public async Task<ActionResult<UserDto>> Create(UserCreateDto d,CancellationToken ct){var role=await db.Roles.FirstOrDefaultAsync(x=>x.Name==d.Role,ct);if(role is null)return BadRequest(new ApiMessage("Role is invalid."));Department? dep=null;if(!string.IsNullOrWhiteSpace(d.Department)){var code=d.Department.Trim().ToUpperInvariant();dep=await db.Departments.FirstOrDefaultAsync(x=>x.Code==code,ct);if(dep is null)return BadRequest(new ApiMessage("Department is invalid."));}var email=d.Email.Trim().ToLowerInvariant();var student=await db.Students.FirstOrDefaultAsync(x=>x.Email==email,ct);var faculty=await db.Faculty.FirstOrDefaultAsync(x=>x.Email==email,ct);var x=new UserAccount{Name=d.Name.Trim(),Email=email,PasswordHash=passwords.Hash(d.Password),Role=role,Department=dep,Student=student,Faculty=faculty,Status=d.Status,Avatar=d.Avatar,Color=d.Color};db.Users.Add(x);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(GetById),new{id=x.Id},new UserDto(x.Id,x.Name,x.Email,role.Name,dep?.Code??"",x.Status,x.LastLoginUtc,x.Avatar,x.Color));}
 [HttpPut("{id:guid}")] public async Task<ActionResult> Update(Guid id,UserUpdateDto d,CancellationToken ct){var x=await db.Users.FindAsync([id],ct);if(x is null)return NotFound();var role=await db.Roles.FirstOrDefaultAsync(a=>a.Name==d.Role,ct);if(role is null)return BadRequest(new ApiMessage("Role is invalid."));Department? dep=null;if(!string.IsNullOrWhiteSpace(d.Department)){var code=d.Department.Trim().ToUpperInvariant();dep=await db.Departments.FirstOrDefaultAsync(a=>a.Code==code,ct);if(dep is null)return BadRequest(new ApiMessage("Department is invalid."));}x.Name=d.Name.Trim();x.Role=role;x.Department=dep;x.Status=d.Status;x.Avatar=d.Avatar;x.Color=d.Color;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("{id:guid}/reset-password")] public async Task<ActionResult<ApiMessage>> ResetPassword(Guid id,[FromBody] string newPassword,CancellationToken ct){if(string.IsNullOrWhiteSpace(newPassword)||newPassword.Length<8)return BadRequest(new ApiMessage("Password must contain at least 8 characters."));var x=await db.Users.FindAsync([id],ct);if(x is null)return NotFound();x.PasswordHash=passwords.Hash(newPassword);await db.SaveChangesAsync(ct);return Ok(new ApiMessage("Password reset successfully."));}
 [HttpDelete("{id:guid}")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.Users.FindAsync([id],ct);if(x is null)return NotFound();db.Users.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
}
