import { useCallback, useEffect, useState } from 'react';
import { api } from '../api/client.js';
import { useAuth } from '../context/AuthContext.jsx';
import { useToast } from '../context/ToastContext.jsx';
import Icon from '../components/Icon.jsx';
import StatusBadge from '../components/StatusBadge.jsx';

export default function NotificationsPage(){const {user}=useAuth();const {showToast}=useToast();const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const canCreate=['Admin','Principal','HOD'].includes(user.role);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.notifications.list({page:1,pageSize:100});setRows(r.items||r||[]);}catch(e){showToast(e.message,'error');}finally{setLoading(false);}},[showToast]);useEffect(()=>{load();},[load]);
 async function mark(id){try{await api.notifications.markRead(id);await load();}catch(e){showToast(e.message,'error');}} async function remove(id){try{await api.notifications.remove(id);showToast('Notification deleted');await load();}catch(e){showToast(e.message,'error');}}
 async function create(){const title=prompt('Notification title');if(!title)return;const recipient=prompt('Recipient name or email');if(!recipient)return;const message=prompt('Message')||'';try{await api.notifications.create({title,user:recipient,message,type:'General'});showToast('Notification sent');await load();}catch(e){showToast(e.message,'error');}}
 return <><div className="page-header page-header-row"><div><h1>Notifications</h1><p>Personal and system notifications</p></div><div className="page-actions">{canCreate&&<button className="btn btn-accent" onClick={create}><Icon name="add"/>New Notification</button>}<button className="btn btn-outline" onClick={async()=>{await api.notifications.markAllRead();await load();}}>Mark all read</button></div></div><div className="notification-list">{loading?<div className="chart-card">Loading...</div>:rows.map(n=><article className={`notification-card ${n.read?'read':''}`} key={n.id}><div className="notification-icon"><Icon name="notifications"/></div><div className="notification-content"><div className="notification-heading"><h3>{n.title}</h3><StatusBadge value={n.read?'Read':'Unread'}/></div><p>{n.message}</p><small>{n.user} · {new Date(n.date).toLocaleString('en-IN')} · {n.type}</small></div><div className="row-actions">{!n.read&&<button className="action-btn" onClick={()=>mark(n.id)}>✓</button>}<button className="action-btn danger" onClick={()=>remove(n.id)}>×</button></div></article>)}{!loading&&!rows.length&&<div className="chart-card empty-message">No notifications found.</div>}</div></>}
